from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtSql import QSqlDatabase, QSqlQuery
from PyQt6.QtWidgets import QWidget

class Ui_Form(QWidget):
    def __init__(self, con):
        super(Ui_Form, self).__init__()
        self.setObjectName("Form")
        self.resize(551, 546)
        self.con = con
        self.flag = ''
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_id = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_id.setFont(font)
        self.l_id.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_id.setObjectName("l_id")
        self.verticalLayout.addWidget(self.l_id)
        self.id = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.verticalLayout.addWidget(self.id)
        self.l_name = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_name.setFont(font)
        self.l_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_name.setObjectName("l_name")
        self.verticalLayout.addWidget(self.l_name)
        self.name = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.l_stepen = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_stepen.setFont(font)
        self.l_stepen.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_stepen.setObjectName("l_stepen")
        self.verticalLayout.addWidget(self.l_stepen)
        self.stepen = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stepen.setFont(font)
        self.stepen.setObjectName("stepen")
        self.verticalLayout.addWidget(self.stepen)
        self.l_zerno = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_zerno.setFont(font)
        self.l_zerno.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_zerno.setObjectName("l_zerno")
        self.verticalLayout.addWidget(self.l_zerno)
        self.zerno = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zerno.setFont(font)
        self.zerno.setEditable(True)
        self.zerno.setObjectName("zerno")
        self.verticalLayout.addWidget(self.zerno)
        self.l_vkus = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_vkus.setFont(font)
        self.l_vkus.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_vkus.setObjectName("l_vkus")
        self.verticalLayout.addWidget(self.l_vkus)
        self.vkus = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vkus.setFont(font)
        self.vkus.setObjectName("vkus")
        self.verticalLayout.addWidget(self.vkus)
        self.l_price = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_price.setFont(font)
        self.l_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_price.setObjectName("l_price")
        self.verticalLayout.addWidget(self.l_price)
        self.price = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.verticalLayout.addWidget(self.price)
        self.l_objem = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_objem.setFont(font)
        self.l_objem.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.l_objem.setObjectName("l_objem")
        self.verticalLayout.addWidget(self.l_objem)
        self.objem = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.objem.setFont(font)
        self.objem.setObjectName("objem")
        self.verticalLayout.addWidget(self.objem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        self.cancel = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.widget)


        self.id.setEnabled(False)
        self.zerno.addItems(['молотый', 'в зернах'])
        self.save.clicked.connect(self.onSave)
        self.cancel.clicked.connect(self.onCancel)

        self.setWindowTitle("Form")
        self.l_id.setText("id")
        self.l_name.setText("Наименование сорта")
        self.l_stepen.setText("Степень обжарки")
        self.l_zerno.setText("Молотый / в зернах")
        self.l_vkus.setText("Описание вкуса")
        self.l_price.setText("Цена")
        self.l_objem.setText("Объем упаковки")
        self.save.setText("Сохранить")
        self.cancel.setText("Отмена")

    def onSave(self):
        if self.flag == 'add':
            self.con.open()
            cur = QSqlQuery()
            cur.exec(f"""insert into cofee (name, stepen, zerno, vkus, price, objem) 
                        values ('{self.name.text()}', '{self.stepen.text()}', '{self.zerno.currentText()}', 
                        '{self.vkus.text()}', '{float(self.price.text())}', '{self.objem.text()}')""")
            self.con.close()
            self.destroy()
        else:

            self.name.text()
            self.con.open()
            cur = QSqlQuery()
            cur.exec(f"""update cofee set name = '{self.name.text()}', stepen = '{self.stepen.text()}', 
                        zerno = '{self.zerno.currentText()}', vkus = '{self.vkus.text()}', price = '{float(self.price.text())}', 
                        objem = '{self.objem.text()}'
                        where id = '{int(self.id.text())}'""")
            self.con.close()
            self.destroy()

    def onCancel(self):
        self.destroy()